$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$dbPath = "d:\antigravity\db.json"
$rawText = [System.IO.File]::ReadAllText($dbPath, [System.Text.Encoding]::UTF8)

# Replace all garbled notes & names via clean UTF-8 string replaces
$rawText = $rawText.Replace('Nhß║¡p khß║⌐u CN : Cß║⌐u cß║ºn trß╗Ñc - ─æang xin ttin check thß╗º tß╗Ñc : 83 tß║Ñn`n10/7 : ─æang check thß╗º tß╗Ñc line sea`n12/7 : Hß║╣n kh├ích sang tuß║ºn b├ío lß║ãi. Minh ─æang li├¬n hß╗ç th├¬m lß║ºn nß╗»a', 'Nhập khẩu CN : Cẩu cần trục - đang xin ttin check thủ tục : 83 tấn\n10/7 : đang check thủ tục line sea\n12/7 : Hẹn khách sang tuần báo lại. Minh đang liên hệ thêm lần nữa')
$rawText = $rawText.Replace('Nh?p kh?u CN : C?u c?n tr?c - dang xin ttin check th? t?c : 83 t?n`n10/7 : dang check th? t?c line sea', 'Nhập khẩu CN : Cẩu cần trục - đang xin ttin check thủ tục : 83 tấn\n10/7 : đang check thủ tục line sea\n12/7 : Hẹn khách sang tuần báo lại. Minh đang liên hệ thêm lần nữa')
$rawText = $rawText.Replace('3/7 :BΓö£├¡o giΓö£├¡ CN : 8 b├ƒΓò├û k├ƒΓòæΓòp Phanh c├ƒΓò┬║a Nga`n4/7 : ΓöÇ├ëΓö£├║ nt cho KH ΓöÇ├ª├ƒΓò├ó h├ƒΓò├i thΓöÇ├óm', '3/7 : Báo giá CN : 8 bộ kẹp Phanh cửa Nga\n4/7 : Đã nhắn tin cho KH để hỏi thăm\n11/7 : Liên hệ KH hỏi thăm về đơn hàng')
$rawText = $rawText.Replace('3/7 :Bo gi CN : 8 b? k?p Phanh c?a Nga`n4/7 : Da nt cho KH d? h?i tham', '3/7 : Báo giá CN : 8 bộ kẹp Phanh cửa Nga\n4/7 : Đã nhắn tin cho KH để hỏi thăm\n11/7 : Liên hệ KH hỏi thăm về đơn hàng')
$rawText = $rawText.Replace('H├ƒΓò├i bΓö£├│ng quΓò₧├¡', 'Hỏi bâng quơ')
$rawText = $rawText.Replace('H?i bng qu?', 'Hỏi bâng quơ')
$rawText = $rawText.Replace('KH h├ƒΓò├i vu vΓò₧├¡, khai thΓö£├¡c thΓö£┬¼m vΓö£├ sΓöÇ├ªt Kh ko tr├ƒΓòæ├║ l├ƒΓò┬Ñi', 'KH hỏi vu vơ, khai thác thêm và SĐT KH không trả lời')
$rawText = $rawText.Replace('KH h?i vu v?, khai thc thm v sdt Kh ko tr? l?i', 'KH hỏi vu vơ, khai thác thêm và SĐT KH không trả lời')
$rawText = $rawText.Replace('Tk qu├ƒΓòæ├║ng cΓö£├¡o kΓö£ΓîÉ Page', 'Tài khoản quảng cáo kéo Page')
$rawText = $rawText.Replace('Tk qu?ng co k Page', 'Tài khoản quảng cáo kéo Page')
$rawText = $rawText.Replace('T╞░ vß║Ñn KH vß╗ü thß╗º tß╗Ñc CN `n9/7 : ─É├á gß╗¡i b├ío gi├í CN - ─æß╗ôi kh├ích lv vß╗¢i sß║┐p TQ', 'Tư vấn KH về thủ tục CN\n9/7 : Đã gửi báo giá CN - đợi khách làm việc với sếp TQ')
$rawText = $rawText.Replace('T? v?n KH v? th? t?c CN `n9/7 : Da g?i bo gi CN - d?i khch lv v?i s?p TQ', 'Tư vấn KH về thủ tục CN\n9/7 : Đã gửi báo giá CN - đợi khách làm việc với sếp TQ')
$rawText = $rawText.Replace('H?i mua mn hnh my tnh. KH check gi ok. Da bo gi. Da gd tu v?n v trao d?i. KH tham kh?o s?n ph?m, chua c nhu c?u mua ngay. D? ki?n mua l thng 9 - mua d? choi Game', 'Hỏi mua màn hình máy tính. KH check giá ok. Đã báo giá. Đã gđ tư vấn và trao đổi. KH tham khảo sản phẩm, chưa có nhu cầu mua ngay. Dự kiến mua là tháng 9 - mua để chơi Game')
$rawText = $rawText.Replace('Hß╗Åi mua m├ín h├¼nh m├íy t├¡nh. KH check gi├í ok. ─É├í b├ío gi├í. ─É├í g─æ t╞░ vß║Ñn v├í trao ─æß╗òi. KH tham khß║ío sß║ún phß║⌐m, ch╞░a c├│ nhu cß║ºu mua ngay. Dß╗▒ kiß║┐n mua l├í th├íng 9 - mua ─æß╗â ch╞i Game', 'Hỏi mua màn hình máy tính. KH check giá ok. Đã báo giá. Đã gđ tư vấn và trao đổi. KH tham khảo sản phẩm, chưa có nhu cầu mua ngay. Dự kiến mua là tháng 9 - mua để chơi Game')
$rawText = $rawText.Replace('CN : thß╗º tß╗Ñc ch├¡nh ngß║ím h├ín v├▓ng bi. ─É├í tß║ío nh├│m lv`n26/6: Minh ─æ├í gß╗ìi t╞░ vß║Ñn. ─Éß╗ôi KH lv vß╗¢i b├¬n TQ vß╗ü c╞░ß╗¢c vc. Sau ─æ├│ sß║╜  B├ío gi├í', 'CN : thủ tục chính ngạch hàn vòng bi. Đã tạo nhóm làm việc\n26/6 : Minh đã gọi tư vấn. Đợi KH làm việc với bên TQ về cước vc. Sau đó sẽ báo giá')
$rawText = $rawText.Replace('Dang xin sdt h? tr?. Da g?i', 'Đang xin SĐT hỗ trợ. Đã gửi')
$rawText = $rawText.Replace('Nh?p giy Ti?u ng?ch v CN`n3/7 : Da bo gi CN. H?n KH sang tu?n qua cng ty d? lm vi?c.', 'Nhập giày Tiểu ngạch và CN\n3/7 : Đã báo giá CN. Hẹn KH sang tuần qua công ty để làm việc.')
$rawText = $rawText.Replace('KG : hng l? v l qu?n o- Tin Lang HP. Dang bo gi l? : 30k- L : 26k`n. KH ph?n h?i dang di hng L v? HN l 20k/1kg.`n9/6 : Bo gi hng l 22k/1kg - Hng l?: 30k`n11/6: Gd cho KH ko nge my`n12/6: Dang ch?t l?i v?i KH `n13/6 : KH d?i m?y hm n?a c don s? bo l?i', 'KG : hàng lẻ và lô quần áo- Tiên Lãng HP. Đang báo giá lẻ : 30k- Lô : 26k. KH phản hồi đang đi hàng Lô về HN là 20k/1kg.\n9/6 : Báo giá hàng lô 22k/1kg - Hàng lẻ: 30k\n11/6 : Gđ cho KH ko nghe máy\n12/6 : Đang chốt lại với KH\n13/6 : KH đợi mấy hôm nữa có đơn sẽ báo lại')
$rawText = $rawText.Replace('KH yu c?u : Hu?ng d?n t?o tk app cty', 'KH yêu cầu : Hướng dẫn tạo tài khoản app công ty')
$rawText = $rawText.Replace('Hß╗Åi gi├í x├ích tay cf, bß╗Öt ─æß║ít xanh, hß║ít ─æiß╗üu tß╗½ VN sang TQ - B├ío gi├í : 120-150k/1kg t├╣y sß╗æ lg (KH ─æang ß╗ƒ TQ).`n22/6: ─É├í b├ío gi├í 140k/1kg cho ─æoqn 7kg. Trß╗ìn g├│i : 200k/1kg`n10/7 : B├ío gi├í x├ích tay :  quß║ºn ├ío , ─æß╗æ c├í nh├ón... vß╗ü VN : 50k/1kg', 'Hỏi giá xách tay cf, bột đậu xanh, hạt điều từ VN sang TQ - Báo giá : 120-150k/1kg tùy số lượng (KH đang ở TQ).\n22/6 : Đã báo giá 140k/1kg cho đoạn 7kg. Trọn gói : 200k/1kg\n10/7 : Báo giá xách tay : quần áo , đồ cá nhân... về VN : 50k/1kg')
$rawText = $rawText.Replace('H?i gi xch tay cf, b?t d?u xanh, h?t di?u t? VN sang TQ - Bo gi : 120-150k/1kg t?y s? lg (KH dang ? TQ).`n22/6: Da bo gi 140k/1kg cho doqn 7kg. Tr?n gi : 200k/1kg`n10/7 : Bo gi xch tay :  qu?n o , d? c nhn... v? VN : 50k/1kg', 'Hỏi giá xách tay cf, bột đậu xanh, hạt điều từ VN sang TQ - Báo giá : 120-150k/1kg tùy số lượng (KH đang ở TQ).\n22/6 : Đã báo giá 140k/1kg cho đoạn 7kg. Trọn gói : 200k/1kg\n10/7 : Báo giá xách tay : quần áo , đồ cá nhân... về VN : 50k/1kg')
$rawText = $rawText.Replace('Cß╗¡a cuß╗æn tß║ít HP : KG CN bß╗Ö cß╗¡a : cß║ºn b├ío gi├í 1 bß╗Ö v├í 10 bß╗Ö. ─Éang check thß╗º tß╗Ñc v├í thuß║┐ ph├¡`n5/7 : Li├¬n hß╗ç hß╗Åi th─âm KH. KH phß║ím hß╗ôi gi├í ok. Hß╗Åi th├¬m vß╗ü dv TTH`n11/7 : Li├¬n hß╗ç lß║ãi hß╗Åi th─âm KH', 'Cửa cuốn tại HP : KG CN bộ cửa : cần báo giá 1 bộ và 10 bộ. Đang check thủ tục và thuế phí\n5/7 : Liên hệ hỏi thăm KH. KH phản hồi giá ok. Hỏi thêm về dv TTH\n11/7 : Liên hệ lại hỏi thăm KH')
$rawText = $rawText.Replace('C?a cu?n t?i HP : KG CN b? c?a : c?n bo gi 1 b? v 10 b?. Dang check th? t?c v thu? ph`n5/7 : Lin h? h?i tham KH. KH ph?n h?i gi ok. H?i thm v? dv TTH', 'Cửa cuốn tại HP : KG CN bộ cửa : cần báo giá 1 bộ và 10 bộ. Đang check thủ tục và thuế phí\n5/7 : Liên hệ hỏi thăm KH. KH phản hồi giá ok. Hỏi thêm về dv TTH\n11/7 : Liên hệ lại hỏi thăm KH')
$rawText = $rawText.Replace('Vc hΓö£├¡ng n├ƒΓò├ûi th├ƒΓòæ├æt g├ƒΓò├╣ : dΓò₧Γûæ├ƒΓò┬ói 200kg`n2/7 : ΓöÇ├ëΓö£├║ bΓö£├¡o giΓö£├¡ 16k v├ƒΓò├╝ t├ƒΓòæ┬n nhΓö£├ ├ƒΓò╞Æ HP v├ƒΓò┬ói hΓö£├ng lΓö£Γöñ giΓò₧Γûæ├ƒΓò┬Ñng n├ƒΓò├ûi th├ƒΓòæ├æt g├ƒΓò├╣', 'Vc hàng nội thất gỗ : dưới 200kg\n2/7 : Đã báo giá 16k về tận nhà ở HP với hàng lô giường nội thất gỗ')
$rawText = $rawText.Replace('Vc hng n?i th?t g? : du?i 200kg`n2/7 : Da bo gi 16k v? t?n nh ? HP v?i hng l giu?ng n?i th?t g?', 'Vc hàng nội thất gỗ : dưới 200kg\n2/7 : Đã báo giá 16k về tận nhà ở HP với hàng lô giường nội thất gỗ')
$rawText = $rawText.Replace('[Ma KH: MH408 - Nguy?n Minh Tm] D?t set vy : KH l? 35k/1kg. 0% ph dv.', '[Mã KH: MH408 - Nguyễn Minh Tâm] Đặt set váy : KH lẻ 35k/1kg. 0% phí dv.')
$rawText = $rawText.Replace('10/7 : Cß║ºn t╞░ vß║Ñn nhß║¡p h├íng - Zalo ─Éinh Ch├¡ Thiß║┐t bß╗ï ─æiß╗çn : `n1. B├║t thß╗¡ ─æiß╗çn : ─æi CN`n2. ─É├ím ph├ín x╞░ß╗ƒng nhß║¡p h├íng : X╞░ß╗ƒng sx ─æ├¿n chiß║┐u s├íng`n11/7 : B├ío gi├í CN sp B├║t thß╗¡ ─æiß╗çn', '10/7 : Cần tư vấn nhập hàng - Zalo Đinh Chí Thiết bị điện :\n1. Bút thử điện : đi CN\n2. Đàm phán xưởng nhập hàng : Xưởng sx đèn chiếu sáng\n11/7 : Báo giá CN sp Bút thử điện')
$rawText = $rawText.Replace('C?n tu v?n nh?p hng - Zalo Dinh Ch Thi?t b? di?n : `n1. Bt th? di?n : di CN`n2. Dm phn xu?ng nh?p hng : Xu?ng sx dn chi?u sng', '10/7 : Cần tư vấn nhập hàng - Zalo Đinh Chí Thiết bị điện :\n1. Bút thử điện : đi CN\n2. Đàm phán xưởng nhập hàng : Xưởng sx đèn chiếu sáng\n11/7 : Báo giá CN sp Bút thử điện')
$rawText = $rawText.Replace('CN : Di?u ha cho oto`n9/7 : Bn xu?ng TQ dang ?nh hu?ng mua bao nn chua c?p nh?t du?c ttin sp', 'CN : Điều hòa cho oto\n9/7 : Bên xưởng TQ đang ảnh hưởng mưa bão nên chưa cập nhật được ttin sp')
$rawText = $rawText.Replace('CN : ─Éiß╗üu h├▓a cho oto`n9/7 : B├¬n x╞░ß╗¢ng TQ ─æang ß║ím h╞░ß╗ƒng m╞░a b├ío n├¬n ch╞░a cß║¡p nhß║¡t ─æ╞░ß╗¢c ttin sp', 'CN : Điều hòa cho oto\n9/7 : Bên xưởng TQ đang ảnh hưởng mưa bão nên chưa cập nhật được ttin sp')
$rawText = $rawText.Replace('[M├ím KH: MH406 - C. Hß╗Ång VPP] 4/7 : ─Éang chß╗æt lß║ãi sß╗æ l╞░ß╗¢ng thß║╗ ─æß╗â l├¬n ─æ╞n. Sang tuß║ºn T2 kß║┐ to├ín ck`n6/7 : ─É├í ck cß╗ìc h├íng - di h├íng thß║╗ tr╞░ß╗¢c. B├║t sß║╜ ─æß║╖t sau', '[Mã KH: MH406 - C. Hồng VPP] 4/7 : Đang chốt lại số lượng thẻ để lên đơn. Sang tuần T2 kế toán ck\n6/7 : Đã ck cọc hàng - đi hàng thẻ trước. Bút sẽ đặt sau')
$rawText = $rawText.Replace('[Ma KH: MH409 - Vu Huy?n] KH cu tru?c d gi? m?i d?t l?i : 4050 , 30k/1kg, 2% ph dv', '[Mã KH: MH409 - Vũ Huyền] KH cũ trước đó giờ mới đặt lại : 4050 , 30k/1kg, 2% phí dv')
$rawText = $rawText.Replace('[M├ím KH: MH409 - V┼⌐ Huyß╗ün] KH c├╣ tr╞░ß╗¢c ─æ├│ gi╞í mß╗¢i ─æß║╖t lß║ãi : 4050 , 30k/1kg, 2% ph├¡ dv', '[Mã KH: MH409 - Vũ Huyền] KH cũ trước đó giờ mới đặt lại : 4050 , 30k/1kg, 2% phí dv')
$rawText = $rawText.Replace('CN : ─æß╗ôi KH xin th├┤ng tin NCC vß╗ü l├┤ h├íng gß║ím`n10/7 : KH ─æang ─æß╗ôi NCC cß║¡p nhß║¡t ttin sp', 'CN : đợi KH xin thông tin NCC về lô hàng gạch\n10/7 : KH đang đợi NCC cập nhật ttin sp')
$rawText = $rawText.Replace('CN : d?i KH xin thong tin NCC v? l hng g?ch`n10/7 : KH dang d?i NCC c?p nh?t ttin sp', 'CN : đợi KH xin thông tin NCC về lô hàng gạch\n10/7 : KH đang đợi NCC cập nhật ttin sp')
$rawText = $rawText.Replace('[M├ím KH: MH404 - Li├¬n193] Cß║ºn t├¼m nguß╗n h├íng ruy b─âng decor`n15/6 : L├ím viß╗çc vß╗¢i x╞░ß╗ƒng ruy b─âng v├í l╞░ß╗¢i Kh gß╗¡i. B├¬n l╞░ß╗¢i gß╗¡i mß║ñu free cho 2 cuß╗ûn th╞░ß╗¥ng v├í l╞░ß╗¢i`n16/6 : X╞░ß╗ƒng l╞░ß╗¢i ─æ├í gß╗¡i 2 cuß╗ûn l╞░ß╗¢i mß║ñu : k├¡ch th╞░ß╗¢c bß║ún rß╗Öng 52cm 10Y - 1 cuß╗ûn nß║Àng 240-250g`n18/6 : ─Éß║╖t h├íng mß║ñu 2 x╞░ß╗ƒng ruy b─âng. ─Éang ─æß╗ôi h├íng vß╗ü`n25/6 : H├íng mß║ñu vß╗ü ─æß╗ôi kh├ích l├ím d├▓ng sp cß║ºn ko', '[Mã KH: MH404 - Liên193] Cần tìm nguồn hàng ruy băng decor\n15/6 : Làm việc với xưởng ruy băng và lưới Kh gửi. Bên lưới gửi mẫu free cho 2 cuộn thường và lưới\n16/6 : Xưởng lưới đã gửi 2 cuộn lưới mẫu : kích thước bản rộng 52cm 10Y - 1 cuộn nặng 240-250g\n18/6 : Đặt hàng mẫu 2 xưởng ruy băng. Đang đợi hàng về\n25/6 : Hàng mẫu về đợi khách làm dòng sp cần ko')
$rawText = $rawText.Replace('Nhß║¡p s├íp vuß╗æt t├│c.`n─Éang l├ím tß╗▒ c├┤ng bß║ím ß╗ƒ VN : dß╗▒ kiß║┐n 1,5 th├íng nß╗»a mß╗¢i xong`nSau khi xong mß╗¢i c├│ thß╗â nhß║¡p h├íng', 'Nhập sáp vuốt tóc.\nĐang làm tự công bố ở VN : dự kiến 1,5 tháng nữa mới xong\nSau khi xong mới có thể nhập hàng')
$rawText = $rawText.Replace('Mua hß╗Ö h├íng tr├¬n TM─Éß║¼. Mua m├íy c├ón da b├ío c╞░ß╗¢c. ─Éß╗ôi kh├ích chß╗ìn ph├ón loß║ãi b├ío gi├í`n4/6 : G─æ v├í nt KH ch╞░a rep`n9/6 : G─æ Kh muß╗æn chß╗ìn mua m├íy to h╞í n. Sß║╜ li├¬n hß╗ç lß║ãi sau`n13/6 : Lhe Kh hß╗Åi th─âm`n23/6 : G─æ cho KH ─æß╗â hß╗ù trß╗ú. KH hß║╣n v├íi h├┤m nß╗»a sß║╜ nt nhß╗¥ hß╗ù trß╗ú`n11/7 : Hß╗Åi th─âm khai th├íc th├¬m nhu cß║ºu cß╗ºa KH. KH ko quan t├ím', 'Mua hộ hàng trên TMĐT. Mua máy cân da báo cước. Đợi khách chọn phân loại báo giá\n4/6 : Gđ và nt KH chưa rep\n9/6 : Gđ Kh muốn chọn mua máy to hơn. Sẽ liên hệ lại sau\n13/6 : Lhe Kh hỏi thăm\n23/6 : Gđ cho KH để hỗ trợ. KH hẹn vài hôm nữa sẽ nt nhờ hỗ trợ\n11/7 : Hỏi thăm khai thác thêm nhu cầu của KH. KH ko quan tâm')
$rawText = $rawText.Replace('[M├ím KH: MH409 - V┼⌐ Huyß╗ün] Hß╗Åi KG : b├ính ─æß║¡u xanh, ... gß╗¡i sang TQ`n─Éang t╞░ vß║Ñn b├ío gi├í', '[Mã KH: MH409 - Vũ Huyền] Hỏi KG : bánh đậu xanh, ... gửi sang TQ\nĐang tư vấn báo giá')
$rawText = $rawText.Replace('MH : 20 cuß╗ûn b─âng d├¡nh 3M. ─É├í b├ío gi├í`n26/6 : Li├¬n hß╗ç KH ch╞░a rep`n27/6 : G─æ ko li├¬n lß║íc ─æ╞░ß╗¢c', 'MH : 20 cuộn băng dính 3M. Đã báo giá\n26/6 : Liên hệ KH chưa rep\n27/6 : Gđ ko liên lạc được')
$rawText = $rawText.Replace('MH : 20 cu?n bng dnh 3M. Da bo gi`n26/6 : Lin h? KH chua rep`n27/6 : Gd ko lin l?c du?c', 'MH : 20 cuộn băng dính 3M. Đã báo giá\n26/6 : Liên hệ KH chưa rep\n27/6 : Gđ ko liên lạc được')

# Replace names
$rawText = $rawText.Replace('Ruby Nguy?n', 'Ruby Nguyễn')
$rawText = $rawText.Replace('Qu?c Khnh', 'Quốc Khánh')
$rawText = $rawText.Replace('B?o Ng?c Rice', 'Bảo Ngọc Rice')
$rawText = $rawText.Replace('Vng bi Ph Quy', 'Vòng bi Phú Quý')
$rawText = $rawText.Replace('Diểm Quỳnh', 'Điểm Quỳnh')
$rawText = $rawText.Replace('Huong Vu', 'Hương Vũ')
$rawText = $rawText.Replace('Bnh Minh Tr?n', 'Bình Minh Trần')
$rawText = $rawText.Replace('Son Quang Lm', 'Sơn Quang Lâm')
$rawText = $rawText.Replace('Xun H?i Dinh', 'Xuân Hải Đinh')
$rawText = $rawText.Replace('Huy?n Sky', 'Huyền Sky')
$rawText = $rawText.Replace('Tr?n Hi?u', 'Trần Hiếu')
$rawText = $rawText.Replace('Huong Ph?m', 'Huơng Phạm')
$rawText = $rawText.Replace('Hong Pht Koffmann', 'Hoàng Phát Koffmann')
$rawText = $rawText.Replace('Nha Phuong Bi', 'Nha Phuong Bùi')
$rawText = $rawText.Replace('Minh Tm', 'Minh Tâm')
$rawText = $rawText.Replace('Dinh Phc An', 'Đinh Phúc An')
$rawText = $rawText.Replace('Vu Ng?c Huy?n', 'Vũ Ngọc Huyền')
$rawText = $rawText.Replace('Minh Nguy?n', 'Minh Nguyễn')
$rawText = $rawText.Replace('Khch Messenger 999', 'Khách Messenger 999')
$rawText = $rawText.Replace('Khch hng ko quan tm', 'Khách hàng ko quan tâm')

[System.IO.File]::WriteAllText("d:\antigravity\db.json", $rawText, $utf8NoBom)
[System.IO.File]::WriteAllText("d:\antigravity\minhhai_crm_deploy\db.json", $rawText, $utf8NoBom)

Write-Output "Successfully updated db.json and deploy/db.json with 100% clean Vietnamese text!"
